# Generated by Django 3.0.4 on 2020-05-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200503_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='last_updated_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
